### ISSUE TITLE
Please add redis broker support

### ISSUE THREAD

**Issue by gjcarneiro** [tomologic/flower#4]
I get the tracback below when trying to use redis as broker.  You need to add redis to the requirements.txt:

```
redis==2.10.3
```

Preferably also add hiredis, but it might require some redis C library to be installed in the container, so I don't know if it works in the `python:3.4.2-onbuild` container:

```
hiredis==0.2.0
```

```
Using broker URL: redis://mollymq.gambit:16380
[I 150716 14:49:32 command:111] Visit me at http://0.0.0.0:8080
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/usr/local/lib/python3.4/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python3.4/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.4/site-packages/celery/bin/base.py", line 307, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.4/site-packages/celery/bin/celery.py", line 761, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python3.4/site-packages/celery/bin/celery.py", line 693, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python3.4/site-packages/flower/command.py", line 88, in run_from_argv
    self.print_banner('ssl_options' in settings)
  File "/usr/local/lib/python3.4/site-packages/flower/command.py", line 112, in print_banner
    logger.info('Broker: %s', self.app.connection().as_uri())
  File "/usr/local/lib/python3.4/site-packages/kombu/connection.py", line 573, in as_uri
    if self.transport.can_parse_url:
  File "/usr/local/lib/python3.4/site-packages/kombu/connection.py", line 769, in transport
    self._transport = self.create_transport()
  File "/usr/local/lib/python3.4/site-packages/kombu/connection.py", line 514, in create_transport
    return self.get_transport_cls()(client=self)
  File "/usr/local/lib/python3.4/site-packages/kombu/transport/redis.py", line 919, in __init__
    raise ImportError('Missing redis library (pip install redis)')
ImportError: Missing redis library (pip install redis)
```

**Comment by gjcarneiro** [comment]
You can safely add hiredis to requirements.txt: I tested it locally, and it builds fine (and works fine too).

**Comment by stanislavb** [comment]
Thanks a lot for testing this!
